// packages/renderer-react/src/components/GroupRenderer.tsx
import React, { useMemo } from 'react'
import { H5Element, DataBindingManager, CANVAS_WIDTH, CANVAS_HEIGHT } from '@year-report/core'
import { ElementRenderer } from './ElementRenderer'

interface GroupBounds {
  x: number
  y: number
  width: number
  height: number
}

interface GroupRendererProps {
  elements: H5Element[]
  rotation: number
  onElementClick?: (element: H5Element) => void
  dataBindingManager?: DataBindingManager | null
}

export const GroupRenderer: React.FC<GroupRendererProps> = ({
  elements,
  rotation,
  onElementClick,
  dataBindingManager
}) => {
  // 计算分组边界
  const bounds = useMemo((): GroupBounds => {
    if (elements.length === 0) {
      return { x: 0, y: 0, width: 0, height: 0 }
    }

    let minX = Infinity
    let minY = Infinity
    let maxX = -Infinity
    let maxY = -Infinity

    elements.forEach(el => {
      const right = el.x + el.width
      const bottom = el.y + el.height
      minX = Math.min(minX, el.x)
      minY = Math.min(minY, el.y)
      maxX = Math.max(maxX, right)
      maxY = Math.max(maxY, bottom)
    })

    return {
      x: minX,
      y: minY,
      width: maxX - minX,
      height: maxY - minY
    }
  }, [elements])

  // 计算缩放后的边界
  const scaledBounds = useMemo(() => {
    const scaleX = window.innerWidth / CANVAS_WIDTH
    const scaleY = window.innerHeight / CANVAS_HEIGHT
    const scale = Math.min(scaleX, scaleY)

    return {
      x: bounds.x * scale,
      y: bounds.y * scale,
      width: bounds.width * scale,
      height: bounds.height * scale
    }
  }, [bounds])

  // 包装器样式
  const wrapperStyle: React.CSSProperties = useMemo(() => ({
    position: 'absolute',
    left: `${scaledBounds.x}px`,
    top: `${scaledBounds.y}px`,
    width: `${scaledBounds.width}px`,
    height: `${scaledBounds.height}px`,
    transform: rotation ? `rotate(${rotation}deg)` : undefined,
    transformOrigin: 'center center',
    pointerEvents: 'none' as const
  }), [scaledBounds, rotation])

  return (
    <div style={wrapperStyle}>
      {elements.map(element => (
        <ElementRenderer
          key={element.id}
          element={element}
          pageIndex={0} // 分组渲染时 pageIndex 不是必需的
          onElementClick={onElementClick}
          dataBindingManager={dataBindingManager}
        />
      ))}
    </div>
  )
}

// packages/renderer-vue2/src/GroupRenderer.vue
<template>
  <div class="groupWrapper" :style="wrapperStyle">
    <ElementRenderer
      v-for="el in elements"
      :key="el.id"
      :element="el"
      :page-index="pageIndex"
      :is-active="isActive"
      :offset-x="-bounds.x"
      :offset-y="-bounds.y"
    />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import type { H5Element } from '@year-report/core'
import ElementRenderer from './ElementRenderer.vue'

interface GroupBounds {
  x: number
  y: number
  width: number
  height: number
}

export default Vue.extend({
  name: 'GroupRenderer',

  components: {
    ElementRenderer
  },

  props: {
    elements: {
      type: Array as () => H5Element[],
      required: true
    },
    bounds: {
      type: Object as () => GroupBounds,
      required: true
    },
    rotation: {
      type: Number,
      default: 0
    },
    pageIndex: {
      type: Number,
      required: true
    },
    isActive: {
      type: Boolean,
      required: true
    }
  },

  computed: {
    wrapperStyle(): any {
      return {
        position: 'absolute',
        left: `${this.bounds.x}px`,
        top: `${this.bounds.y}px`,
        width: `${this.bounds.width}px`,
        height: `${this.bounds.height}px`,
        transform: this.rotation ? `rotate(${this.rotation}deg)` : undefined,
        transformOrigin: 'center center'
      }
    }
  }
})
</script>

<style scoped>
.groupWrapper {
  pointer-events: none;
}
</style>
