// packages/renderer-react/src/components/YearReportRenderer.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import 'animate.css'
import { ElementRenderer } from './ElementRenderer'
import { GroupRenderer } from './GroupRenderer'
import { ProjectData, H5Page, H5Element, DataSourceManager } from '@year-report/core'

interface YearReportRendererProps {
  data: ProjectData
  onPageChange?: (pageIndex: number) => void
  onElementClick?: (element: H5Element) => void
}

export const YearReportRenderer: React.FC<YearReportRendererProps> = ({
  data,
  onPageChange,
  onElementClick
}) => {
  const [currentPageIndex, setCurrentPageIndex] = useState(0)
  const [isPlaying, setIsPlaying] = useState(false)
  const [touchStart, setTouchStart] = useState(0)
  const [mouseStart, setMouseStart] = useState(0)
  const [isSwiping, setIsSwiping] = useState(false)

  const audioRef = useRef<HTMLAudioElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const dataSourceManager = useRef<DataSourceManager | null>(null)

  // 初始化数据源
  useEffect(() => {
    if (data.dataSources?.length) {
      dataSourceManager.current = new DataSourceManager()
      dataSourceManager.current.setDataSources(data.dataSources)
    }
    return () => {
      dataSourceManager.current?.destroy()
    }
  }, [data.dataSources])

  // 处理背景音乐
  useEffect(() => {
    if (data.backgroundMusic && audioRef.current) {
      audioRef.current.volume = 0.3
    }
  }, [data.backgroundMusic])

  const toggleMusic = useCallback(() => {
    if (!audioRef.current) return
    if (isPlaying) {
      audioRef.current.pause()
    } else {
      audioRef.current.play().catch(console.error)
    }
    setIsPlaying(!isPlaying)
  }, [isPlaying])

  const getUngroupedElements = useCallback((page: H5Page) => {
    return page.elements.filter(el => !el.groupId)
  }, [])

  const getGroups = useCallback((page: H5Page) => {
    const groups: { [groupId: string]: H5Element[] } = {}
    page.elements.forEach(el => {
      if (el.groupId) {
        if (!groups[el.groupId]) {
          groups[el.groupId] = []
        }
        groups[el.groupId].push(el)
      }
    })
    return groups
  }, [])

  const goToPage = useCallback((index: number) => {
    if (index < 0 || index >= data.pages.length) return
    setCurrentPageIndex(index)
    onPageChange?.(index)
  }, [data.pages.length, onPageChange])

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    setTouchStart(e.touches[0].clientY)
    setIsSwiping(true)
  }, [])

  const handleTouchEnd = useCallback((e: React.TouchEvent) => {
    if (!isSwiping) return
    const touchEnd = e.changedTouches[0].clientY
    const diff = touchStart - touchEnd
    if (Math.abs(diff) > 50) {
      if (diff > 0) {
        goToPage(currentPageIndex + 1)
      } else {
        goToPage(currentPageIndex - 1)
      }
    }
    setIsSwiping(false)
  }, [touchStart, isSwiping, currentPageIndex, goToPage])

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    setMouseStart(e.clientY)
    setIsSwiping(true)
  }, [])

  const handleMouseUp = useCallback((e: React.MouseEvent) => {
    if (!isSwiping) return
    const mouseEnd = e.clientY
    const diff = mouseStart - mouseEnd
    if (Math.abs(diff) > 50) {
      if (diff > 0) {
        goToPage(currentPageIndex + 1)
      } else {
        goToPage(currentPageIndex - 1)
      }
    }
    setIsSwiping(false)
  }, [mouseStart, isSwiping, currentPageIndex, goToPage])

  const getPageStyle = useCallback((page: H5Page) => {
    const style: React.CSSProperties = {}
    if (page.backgroundType === 'color') {
      style.backgroundColor = page.backgroundColor || '#ffffff'
    } else if (page.backgroundType === 'gradient' && page.backgroundGradient) {
      const { type, direction, colors } = page.backgroundGradient
      const colorStops = colors.map(c => `${c.color} ${c.position || ''}`).join(', ')
      if (type === 'linear') {
        style.background = `linear-gradient(${direction || 'to bottom'}, ${colorStops})`
      } else {
        style.background = `radial-gradient(circle, ${colorStops})`
      }
    } else if (page.backgroundType === 'image' && page.backgroundImage) {
      style.backgroundImage = `url(${page.backgroundImage})`
      style.backgroundSize = 'cover'
      style.backgroundColor = page.backgroundColor || '#ffffff'
    } else {
      style.backgroundColor = page.backgroundColor || '#ffffff'
    }
    return style
  }, [])

  const handleElementClick = useCallback((element: H5Element) => {
    onElementClick?.(element)
  }, [onElementClick])

  return (
    <div className="fixedContainer" style={{ width: '100%', height: '100vh', overflow: 'hidden' }}>
      {data.backgroundMusic && (
        <audio ref={audioRef} src={data.backgroundMusic} loop />
      )}
      {data.backgroundMusic && (
        <button
          onClick={toggleMusic}
          style={{
            position: 'fixed',
            top: '20px',
            right: '20px',
            zIndex: 9999,
            width: '40px',
            height: '40px',
            borderRadius: '50%',
            border: 'none',
            background: 'rgba(0, 0, 0, 0.5)',
            color: 'white',
            fontSize: '20px',
            cursor: 'pointer'
          }}
        >
          {isPlaying ? '🔊' : '🔇'}
        </button>
      )}

      <div
        ref={containerRef}
        style={{
          width: '100%',
          height: '100%',
          position: 'relative',
          cursor: isSwiping ? 'grabbing' : 'grab'
        }}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        onMouseDown={handleMouseDown}
        onMouseUp={handleMouseUp}
      >
        <div
          style={{
            width: '100%',
            height: '100%',
            position: 'relative',
            transition: 'transform 0.5s ease-in-out',
            transform: `translateY(-${currentPageIndex * 100}%)`
          }}
        >
          {data.pages.map((page, index) => {
            const groups = getGroups(page)
            return (
              <div
                key={page.id}
                style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: '100%',
                  ...getPageStyle(page),
                  transform: `translateY(${index * 100}%)`
                }}
              >
                {page.backgroundType === 'video' && page.backgroundVideo && (
                  <video
                    src={page.backgroundVideo}
                    style={{
                      position: 'absolute',
                      top: 0,
                      left: 0,
                      width: '100%',
                      height: '100%',
                      objectFit: 'cover',
                      zIndex: 0
                    }}
                    autoPlay
                    loop
                    muted
                    playsInline
                  />
                )}

                {Object.entries(groups).map(([groupId, elements]) => (
                  <GroupRenderer
                    key={groupId}
                    elements={elements}
                    rotation={page.groupRotations?.[groupId] || 0}
                    onElementClick={handleElementClick}
                    dataBindingManager={dataSourceManager.current}
                  />
                ))}

                {getUngroupedElements(page).map(element => (
                  <ElementRenderer
                    key={element.id}
                    element={element}
                    pageIndex={index}
                    onElementClick={handleElementClick}
                    dataBindingManager={dataSourceManager.current}
                  />
                ))}
              </div>
            )
          })}
        </div>

        <div
          style={{
            position: 'fixed',
            right: '20px',
            top: '50%',
            transform: 'translateY(-50%)',
            zIndex: 100,
            display: 'flex',
            flexDirection: 'column',
            gap: '10px'
          }}
        >
          {data.pages.map((_, index) => (
            <div
              key={index}
              onClick={() => goToPage(index)}
              style={{
                width: '10px',
                height: '10px',
                borderRadius: '50%',
                backgroundColor: index === currentPageIndex ? '#fff' : 'rgba(255, 255, 255, 0.5)',
                cursor: 'pointer',
                transition: 'all 0.3s'
              }}
            />
          ))}
        </div>
      </div>
    </div>
  )
}

// packages/renderer-vue3/src/YearReportRenderer.vue
<template>
  <div class="fixedContainer">
    <!-- 背景音乐 -->
    <audio v-if="data.backgroundMusic" ref="audioRef" :src="data.backgroundMusic" loop />
    <button
      v-if="data.backgroundMusic"
      @click="toggleMusic"
      class="musicBtn"
    >
      {{ isPlaying ? '🔊' : '🔇' }}
    </button>

    <!-- 移动端容器 -->
    <div
      class="mobileContainer"
      @touchstart="handleTouchStart"
      @touchend="handleTouchEnd"
      @mousedown="handleMouseDown"
      @mouseup="handleMouseUp"
    >
      <!-- 页面容器 -->
      <div class="pagesContainer" :style="{ transform: `translateY(-${currentIndex * 100}%)` }">
        <div
          v-for="(page, index) in data.pages"
          :key="page.id"
          class="pageItem"
          :style="getPageStyle(page, index)"
        >
          <!-- 背景视频 -->
          <video
            v-if="page.backgroundType === 'video' && page.backgroundVideo"
            :src="page.backgroundVideo"
            class="bgVideo"
            autoplay
            loop
            muted
            playsinline
          />

          <!-- 非分组元素 -->
          <ElementRenderer
            v-for="el in getUngroupedElements(page)"
            :key="el.id"
            :element="el"
            :page-index="index"
            :is-active="index === currentIndex"
          />

          <!-- 分组元素 -->
          <GroupRenderer
            v-for="group in calcGroupBounds(page)"
            :key="group.groupId"
            :elements="group.elements"
            :bounds="group"
            :rotation="page.groupRotations?.[group.groupId] || 0"
            :page-index="index"
            :is-active="index === currentIndex"
          />
        </div>
      </div>

      <!-- 下滑提示 -->
      <div v-if="currentIndex < data.pages.length - 1" class="scrollHint">
        <svg class="chevron" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
        </svg>
      </div>

      <!-- 关闭按钮 -->
      <button v-if="onClose" @click="onClose" class="closeBtn">✕</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, provide, watch, nextTick } from 'vue'
import type { ProjectData, RequestAdapter, H5Element, H5Page } from '@year-report/core'
import { DataSourceManager, AnimateCssScheduler } from '@year-report/core'
import ElementRenderer from './ElementRenderer.vue'
import GroupRenderer from './GroupRenderer.vue'
import 'animate.css'

// 计算分组边界
interface GroupBounds {
  groupId: string
  x: number
  y: number
  width: number
  height: number
  elements: H5Element[]
}

function calcGroupBounds(page: H5Page): GroupBounds[] {
  const groups = new Map<string, H5Element[]>()
  page.elements.forEach(el => {
    if (el.groupId) {
      if (!groups.has(el.groupId)) groups.set(el.groupId, [])
      groups.get(el.groupId)!.push(el)
    }
  })

  const bounds: GroupBounds[] = []
  groups.forEach((elements, groupId) => {
    if (elements.length < 2) return
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
    elements.forEach(el => {
      minX = Math.min(minX, el.x)
      minY = Math.min(minY, el.y)
      maxX = Math.max(maxX, el.x + el.width)
      maxY = Math.max(maxY, el.y + el.height)
    })
    bounds.push({ groupId, x: minX, y: minY, width: maxX - minX, height: maxY - minY, elements })
  })
  return bounds
}

function getUngroupedElements(page: H5Page): H5Element[] {
  return page.elements.filter(el => !el.groupId)
}

interface Props {
  data: ProjectData
  onClose?: () => void
  requestAdapter?: RequestAdapter
}

const props = defineProps<Props>()

// 数据源管理器
const dataManager = new DataSourceManager(props.requestAdapter)
const dataVersion = ref(0)

// 动画编排器（每个页面一个）
const pageSchedulers = ref<Map<number, AnimateCssScheduler>>(new Map())

// 提供给子组件
provide('dataManager', dataManager)
provide('dataVersion', dataVersion)
provide('pageSchedulers', pageSchedulers)

const currentIndex = ref(0)
const prevIndex = ref(-1)
const touchStartY = ref<number | null>(null)
const audioRef = ref<HTMLAudioElement | null>(null)
const isPlaying = ref(false)

// 监听页面切换，播放动画
watch(currentIndex, (newIndex, oldIndex) => {
  // 播放退出动画
  if (oldIndex >= 0) {
    const oldScheduler = pageSchedulers.value.get(oldIndex)
    oldScheduler?.playExitAnimations()
  }

  // 播放进入动画（等待 DOM 更新）
  nextTick(() => {
    setTimeout(() => {
      const scheduler = pageSchedulers.value.get(newIndex)
      scheduler?.playEnterAnimations()
    }, 100)
  })

  prevIndex.value = oldIndex
}, { immediate: true })

// 注入动画样式和初始化数据源
onMounted(() => {
  // 初始化数据源
  if (props.data.dataSources?.length) {
    dataManager.subscribe(() => {
      dataVersion.value++
    })
    dataManager.setDataSources(props.data.dataSources)
  }

  // 自动播放音乐
  if (audioRef.value) {
    audioRef.value.play().then(() => {
      isPlaying.value = true
    }).catch(() => {
      isPlaying.value = false
    })
  }
})

onUnmounted(() => {
  dataManager.destroy()
})

// 获取页面样式（支持渐变）
const getPageStyle = (page: H5Page, index: number) => {
  const style: any = {
    top: `${index * 100}%`
  }

  if (page.backgroundType === 'color') {
    style.backgroundColor = page.backgroundColor || '#ffffff'
  } else if (page.backgroundType === 'gradient' && page.backgroundGradient) {
    const { type, direction, colors } = page.backgroundGradient
    const colorStops = colors.map(c => `${c.color} ${c.position || ''}`).join(', ')
    if (type === 'linear') {
      style.background = `linear-gradient(${direction || 'to bottom'}, ${colorStops})`
    } else {
      style.background = `radial-gradient(circle, ${colorStops})`
    }
  } else if (page.backgroundType === 'image' && page.backgroundImage) {
    style.backgroundImage = `url(${page.backgroundImage})`
    style.backgroundSize = 'cover'
    style.backgroundColor = page.backgroundColor || '#ffffff'
  } else {
    style.backgroundColor = page.backgroundColor || '#ffffff'
  }

  return style
}

const toggleMusic = () => {
  if (!audioRef.value) return
  if (isPlaying.value) {
    audioRef.value.pause()
  } else {
    audioRef.value.play()
  }
  isPlaying.value = !isPlaying.value
}

const handleTouchStart = (e: TouchEvent) => {
  touchStartY.value = e.touches[0].clientY
}

const handleTouchEnd = (e: TouchEvent) => {
  if (touchStartY.value === null) return
  const touchEndY = e.changedTouches[0].clientY
  const diff = touchStartY.value - touchEndY

  if (Math.abs(diff) > 50) {
    if (diff > 0 && currentIndex.value < props.data.pages.length - 1) {
      currentIndex.value++
    } else if (diff < 0 && currentIndex.value > 0) {
      currentIndex.value--
    }
  }
  touchStartY.value = null
}

const handleMouseDown = (e: MouseEvent) => {
  touchStartY.value = e.clientY
}

const handleMouseUp = (e: MouseEvent) => {
  if (touchStartY.value === null) return
  const diff = touchStartY.value - e.clientY
  if (Math.abs(diff) > 50) {
    if (diff > 0 && currentIndex.value < props.data.pages.length - 1) {
      currentIndex.value++
    } else if (diff < 0 && currentIndex.value > 0) {
      currentIndex.value--
    }
  }
  touchStartY.value = null
}
</script>

<style scoped>
.fixedContainer {
  position: fixed;
  inset: 0;
  z-index: 50;
  background-color: black;
  display: flex;
  align-items: center;
  justify-content: center;
}

.musicBtn {
  position: fixed;
  top: 1rem;
  right: 4rem;
  z-index: 60;
  background-color: rgba(255, 255, 255, 0.2);
  color: white;
  padding: 0.5rem;
  border-radius: 9999px;
  backdrop-filter: blur(12px);
  border: none;
  cursor: pointer;
}

.mobileContainer {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background-color: white;
}

@media (min-width: 768px) {
  .mobileContainer {
    width: 375px;
    height: 667px;
    border-radius: 0.75rem;
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
  }
}

.pagesContainer {
  position: absolute;
  width: 100%;
  height: 100%;
  transition: transform 0.5s ease-in-out;
}

.pageItem {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: hidden;
}

.bgVideo {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  pointer-events: none;
}

.scrollHint {
  position: absolute;
  bottom: 1rem;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  animation: bounce 1s infinite;
  pointer-events: none;
  z-index: 20;
}

.chevron {
  color: rgba(255, 255, 255, 0.5);
  width: 2rem;
  height: 2rem;
}

.closeBtn {
  position: absolute;
  top: 1rem;
  right: 1rem;
  background-color: rgba(0, 0, 0, 0.2);
  color: white;
  padding: 0.5rem;
  border-radius: 9999px;
  border: none;
  cursor: pointer;
  z-index: 50;
  transition: background-color 0.2s;
}

.closeBtn:hover {
  background-color: rgba(0, 0, 0, 0.4);
}

@keyframes bounce {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-0.5rem);
  }
}
</style>
